import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run test:coverage` — not source, never lint it.
    "coverage/**",
    // One-off local diagnostic scripts (plain CommonJS, run by hand via node).
    "*.cjs",
  ]),
  {
    files: ["**/*.{ts,tsx,js,jsx}"],
    rules: {
      // All user confirmations/notices must use the custom ConfirmDialog
      // (see components/ui/confirm-dialog.tsx) so the UX stays consistent.
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "CallExpression[callee.object.name='window'][callee.property.name=/^(confirm|alert|prompt)$/]",
          message:
            "Do not use window.confirm/alert/prompt. Use the ConfirmDialog primitive (components/ui/confirm-dialog.tsx) instead.",
        },
        {
          selector:
            "CallExpression[callee.type='Identifier'][callee.name=/^(confirm|alert|prompt)$/]",
          message:
            "Do not use global confirm/alert/prompt. Use the ConfirmDialog primitive (components/ui/confirm-dialog.tsx) instead.",
        },
      ],
    },
  },
  {
    // ---- Legacy debt baseline (2026-07-20) ----
    // These three rules have pre-existing violations across the app. They are
    // demoted to warnings so `npm run lint:ci` can gate on *errors* today —
    // i.e. no new class of violation can land — while the existing ones stay
    // visible and capped by --max-warnings.
    //
    // The cap only ever moves DOWN. When you fix violations, lower the
    // --max-warnings number in package.json in the same PR. When a rule hits
    // zero, delete its line here so it returns to error.
    //
    //   no-explicit-any          68 — mostly `catch (e: any)` and untyped API
    //                                 payloads; these largely disappear once a
    //                                 typed client is generated from openapi.json.
    //   set-state-in-effect      19 — dialogs seeding form state from props.
    //   static-components        11 — components declared inside components.
    files: ["**/*.{ts,tsx,js,jsx}"],
    rules: {
      "@typescript-eslint/no-explicit-any": "warn",
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/static-components": "warn",
    },
  },
]);

export default eslintConfig;
